name: elite_inpainting
channels:
  - pytorch
  - nvidia
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.6.0
  - aria2=1.23.0
  - blas=1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.7.15
  - cairo=1.18.4
  - certifi=2025.8.3
  - charset-normalizer=3.3.2
  - cuda=11.6.1
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=12.9.79
  - cuda-libraries=11.6.1
  - cuda-libraries-dev=11.6.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.9.79
  - cuda-nsight-compute=12.4.1
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=12.9.88
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=12.9.79
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=12.9.79
  - cuda-runtime=11.6.1
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=12.9.79
  - cuda-toolkit=11.6.1
  - cuda-tools=11.6.1
  - cuda-version=12.9
  - cuda-visual-tools=11.6.1
  - dav1d=1.2.1
  - dbus=1.16.2
  - expat=2.7.1
  - ffmpeg=4.3
  - fontconfig=2.14.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gds-tools=1.14.1.1
  - gmp=6.3.0
  - gnutls=3.6.15
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libavif=1.1.1
  - libcublas=11.9.2.110
  - libcublas-dev=11.9.2.110
  - libcufft=10.7.1.112
  - libcufft-dev=10.7.1.112
  - libcufile=1.14.1.1
  - libcufile-dev=1.14.1.1
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcusolver=11.3.4.124
  - libcusparse=11.7.2.124
  - libcusparse-dev=11.7.2.124
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc=7.2.0
  - libgcc-ng=11.2.0
  - libglib=2.84.2
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.6.3.124
  - libnpp-dev=11.6.3.124
  - libnvjpeg=11.6.2.124
  - libnvjpeg-dev=11.6.2.124
  - libpng=1.6.39
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.5
  - nettle=3.7.3
  - nsight-compute=2025.2.1.3
  - nspr=4.35
  - nss=3.89.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=1.1.1w
  - pcre2=10.42
  - pip=25.2
  - pixman=0.46.4
  - pthread-stubs=0.3
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.9.18
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - pytorch-mutex=1.0
  - readline=8.3
  - sqlite=3.50.2
  - tbb=2021.8.0
  - tk=8.6.15
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - typing_extensions=4.15.0
  - wheel=0.45.1
  - xkeyboard-config=2.44
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.1
      - accelerate==0.16.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - albumentations==1.3.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.10.0
      - argcomplete==3.6.2
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.3.0
      - bcrypt==5.0.0
      - beautifulsoup4==4.14.2
      - boto3==1.40.41
      - botocore==1.40.41
      - brotli==1.1.0
      - cachetools==6.2.0
      - cffi==2.0.0
      - click==8.1.8
      - contourpy==1.3.0
      - crcmod==1.7
      - cryptography==46.0.1
      - cycler==0.12.1
      - dacite==1.9.2
      - deprecated==1.2.18
      - diffusers==0.11.1
      - dill==0.4.0
      - dnspython==2.7.0
      - exceptiongroup==1.3.0
      - fastapi==0.116.1
      - ffmpy==0.6.1
      - fiftyone==1.8.1
      - fiftyone-brain==0.21.3
      - fiftyone-db==1.3.0
      - filelock==3.14.0
      - fonttools==4.59.2
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - ftfy==6.3.1
      - glob2==0.7
      - gradio==3.20.1
      - graphql-core==3.2.6
      - grpcio==1.75.0
      - h11==0.16.0
      - h2==4.3.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.13.0
      - humanize==4.13.0
      - hypercorn==0.17.3
      - hyperframe==6.1.0
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - inflate64==1.0.3
      - jinja2==3.1.6
      - jmespath==0.10.0
      - joblib==1.5.2
      - jsonlines==4.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lia-web==0.2.3
      - linkify-it-py==2.0.3
      - markdown==3.9
      - markdown-it-py==2.2.0
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - mongoengine==0.29.1
      - motor==3.6.1
      - multidict==6.6.4
      - multivolumefile==0.2.3
      - narwhals==2.4.0
      - networkx==3.2.1
      - numpy==1.23.0
      - opencv-python-headless==4.7.0.68
      - openxlab==0.1.2
      - orjson==3.11.3
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.3.2
      - paramiko==3.5.1
      - pillow==9.4.0
      - plotly==6.3.0
      - pprintpp==0.4.0
      - priority==2.0.0
      - propcache==0.3.2
      - protobuf==6.32.1
      - psutil==7.0.0
      - py7zr==1.0.0
      - pybcj==1.0.6
      - pycryptodome==3.23.0
      - pycryptodomex==3.23.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydash==8.0.5
      - pydub==0.25.1
      - pygments==2.19.2
      - pymongo==4.9.2
      - pynacl==1.6.0
      - pyparsing==3.2.3
      - pyppmd==1.2.0
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2023.4
      - pyyaml==6.0.2
      - pyzstd==0.17.0
      - qudida==0.0.4
      - rarfile==4.2
      - referencing==0.36.2
      - regex==2025.9.1
      - requests==2.28.2
      - retrying==1.4.2
      - rich==13.4.2
      - rpds-py==0.27.1
      - rtree==1.4.1
      - s3transfer==0.14.0
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - setuptools==60.2.0
      - six==1.17.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.8
      - sse-starlette==0.10.3
      - sseclient-py==1.8.0
      - starlette==0.47.3
      - strawberry-graphql==0.282.0
      - tabulate==0.9.0
      - taskgroup==0.2.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - tokenizers==0.13.3
      - tomli==2.2.1
      - tqdm==4.65.0
      - transformers==4.26.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - tzlocal==5.3.1
      - uc-micro-py==1.0.3
      - universal-analytics-python3==1.1.1
      - urllib3==1.26.20
      - uvicorn==0.35.0
      - voxel51-eta==0.15.1
      - wcwidth==0.2.14
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.3
      - wsproto==1.2.0
      - xmltodict==1.0.2
      - yarl==1.20.1
      - zipp==3.23.0
